// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/share/:token": {
    params: {
      "token": string;
    };
  };
  "/onboarding": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/jobs": {
    params: {};
  };
  "/jobs/:id": {
    params: {
      "id": string;
    };
  };
  "/saved-searches": {
    params: {};
  };
  "/job-alerts": {
    params: {};
  };
  "/companies": {
    params: {};
  };
  "/companies/:id": {
    params: {
      "id": string;
    };
  };
  "/applications": {
    params: {};
  };
  "/applications/analytics": {
    params: {};
  };
  "/applications/:id": {
    params: {
      "id": string;
    };
  };
  "/interview-prep": {
    params: {};
  };
  "/interview-schedule": {
    params: {};
  };
  "/interview-notes": {
    params: {};
  };
  "/interviewer-feedback": {
    params: {};
  };
  "/mock-interview": {
    params: {};
  };
  "/technical-practice": {
    params: {};
  };
  "/behavioral-bank": {
    params: {};
  };
  "/interview-cheat-sheet": {
    params: {};
  };
  "/panel-interview": {
    params: {};
  };
  "/case-study": {
    params: {};
  };
  "/interview-analytics": {
    params: {};
  };
  "/offers": {
    params: {};
  };
  "/offers/compare": {
    params: {};
  };
  "/offers/negotiate": {
    params: {};
  };
  "/offers/equity": {
    params: {};
  };
  "/offers/benefits": {
    params: {};
  };
  "/offers/decide": {
    params: {};
  };
  "/offers/resign": {
    params: {};
  };
  "/resumes": {
    params: {};
  };
  "/resumes/new": {
    params: {};
  };
  "/resumes/upload": {
    params: {};
  };
  "/resumes/batch": {
    params: {};
  };
  "/resumes/batch/:id": {
    params: {
      "id": string;
    };
  };
  "/resumes/:id": {
    params: {
      "id": string;
    };
  };
  "/resumes/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/resumes/:id/cover-letter": {
    params: {
      "id": string;
    };
  };
  "/resumes/:id/skill-gap": {
    params: {
      "id": string;
    };
  };
  "/resumes/:id/interview-questions": {
    params: {
      "id": string;
    };
  };
  "/resumes/:id/salary-estimate": {
    params: {
      "id": string;
    };
  };
  "/resumes/:id/multi-jd": {
    params: {
      "id": string;
    };
  };
  "/resumes/:id/templates": {
    params: {
      "id": string;
    };
  };
  "/resumes/:id/tailored": {
    params: {
      "id": string;
    };
  };
  "/resumes/:id/versions": {
    params: {
      "id": string;
    };
  };
  "/cover-letter-templates": {
    params: {};
  };
  "/linkedin-profile": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/references": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/wipe": {
    params: {};
  };
  "/onboarding/plan": {
    params: {};
  };
  "/onboarding/checklist": {
    params: {};
  };
  "/onboarding/manager-alignment": {
    params: {};
  };
  "/onboarding/network-map": {
    params: {};
  };
  "/onboarding/skill-refresh": {
    params: {};
  };
  "/onboarding/first-90-days": {
    params: {};
  };
  "/follow-up-emails": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/auth" | "/share/:token" | "/onboarding" | "/dashboard" | "/jobs" | "/jobs/:id" | "/saved-searches" | "/job-alerts" | "/companies" | "/companies/:id" | "/applications" | "/applications/analytics" | "/applications/:id" | "/interview-prep" | "/interview-schedule" | "/interview-notes" | "/interviewer-feedback" | "/mock-interview" | "/technical-practice" | "/behavioral-bank" | "/interview-cheat-sheet" | "/panel-interview" | "/case-study" | "/interview-analytics" | "/offers" | "/offers/compare" | "/offers/negotiate" | "/offers/equity" | "/offers/benefits" | "/offers/decide" | "/offers/resign" | "/resumes" | "/resumes/new" | "/resumes/upload" | "/resumes/batch" | "/resumes/batch/:id" | "/resumes/:id" | "/resumes/:id/edit" | "/resumes/:id/cover-letter" | "/resumes/:id/skill-gap" | "/resumes/:id/interview-questions" | "/resumes/:id/salary-estimate" | "/resumes/:id/multi-jd" | "/resumes/:id/templates" | "/resumes/:id/tailored" | "/resumes/:id/versions" | "/cover-letter-templates" | "/linkedin-profile" | "/portfolio" | "/references" | "/profile" | "/wipe" | "/onboarding/plan" | "/onboarding/checklist" | "/onboarding/manager-alignment" | "/onboarding/network-map" | "/onboarding/skill-refresh" | "/onboarding/first-90-days" | "/follow-up-emails";
  };
  "routes/landing.tsx": {
    id: "routes/landing";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/share.tsx": {
    id: "routes/share";
    page: "/share/:token";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "components/Layout.tsx": {
    id: "components/Layout";
    page: "/dashboard" | "/jobs" | "/jobs/:id" | "/saved-searches" | "/job-alerts" | "/companies" | "/companies/:id" | "/applications" | "/applications/analytics" | "/applications/:id" | "/interview-prep" | "/interview-schedule" | "/interview-notes" | "/interviewer-feedback" | "/mock-interview" | "/technical-practice" | "/behavioral-bank" | "/interview-cheat-sheet" | "/panel-interview" | "/case-study" | "/interview-analytics" | "/offers" | "/offers/compare" | "/offers/negotiate" | "/offers/equity" | "/offers/benefits" | "/offers/decide" | "/offers/resign" | "/resumes" | "/resumes/new" | "/resumes/upload" | "/resumes/batch" | "/resumes/batch/:id" | "/resumes/:id" | "/resumes/:id/edit" | "/resumes/:id/cover-letter" | "/resumes/:id/skill-gap" | "/resumes/:id/interview-questions" | "/resumes/:id/salary-estimate" | "/resumes/:id/multi-jd" | "/resumes/:id/templates" | "/resumes/:id/tailored" | "/resumes/:id/versions" | "/cover-letter-templates" | "/linkedin-profile" | "/portfolio" | "/references" | "/profile" | "/wipe" | "/onboarding/plan" | "/onboarding/checklist" | "/onboarding/manager-alignment" | "/onboarding/network-map" | "/onboarding/skill-refresh" | "/onboarding/first-90-days" | "/follow-up-emails";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/jobs.tsx": {
    id: "routes/jobs";
    page: "/jobs";
  };
  "routes/jobs.$id.tsx": {
    id: "routes/jobs.$id";
    page: "/jobs/:id";
  };
  "routes/saved-searches.tsx": {
    id: "routes/saved-searches";
    page: "/saved-searches";
  };
  "routes/job-alerts.tsx": {
    id: "routes/job-alerts";
    page: "/job-alerts";
  };
  "routes/companies.tsx": {
    id: "routes/companies";
    page: "/companies";
  };
  "routes/companies.$id.tsx": {
    id: "routes/companies.$id";
    page: "/companies/:id";
  };
  "routes/applications.tsx": {
    id: "routes/applications";
    page: "/applications";
  };
  "routes/applications-analytics.tsx": {
    id: "routes/applications-analytics";
    page: "/applications/analytics";
  };
  "routes/application-detail.tsx": {
    id: "routes/application-detail";
    page: "/applications/:id";
  };
  "routes/interview-prep.tsx": {
    id: "routes/interview-prep";
    page: "/interview-prep";
  };
  "routes/interview-schedule.tsx": {
    id: "routes/interview-schedule";
    page: "/interview-schedule";
  };
  "routes/interview-notes.tsx": {
    id: "routes/interview-notes";
    page: "/interview-notes";
  };
  "routes/interviewer-feedback.tsx": {
    id: "routes/interviewer-feedback";
    page: "/interviewer-feedback";
  };
  "routes/mock-interview.tsx": {
    id: "routes/mock-interview";
    page: "/mock-interview";
  };
  "routes/technical-practice.tsx": {
    id: "routes/technical-practice";
    page: "/technical-practice";
  };
  "routes/behavioral-bank.tsx": {
    id: "routes/behavioral-bank";
    page: "/behavioral-bank";
  };
  "routes/interview-cheat-sheet.tsx": {
    id: "routes/interview-cheat-sheet";
    page: "/interview-cheat-sheet";
  };
  "routes/panel-interview.tsx": {
    id: "routes/panel-interview";
    page: "/panel-interview";
  };
  "routes/case-study.tsx": {
    id: "routes/case-study";
    page: "/case-study";
  };
  "routes/interview-analytics.tsx": {
    id: "routes/interview-analytics";
    page: "/interview-analytics";
  };
  "routes/offers.tsx": {
    id: "routes/offers";
    page: "/offers";
  };
  "routes/offer-comparison.tsx": {
    id: "routes/offer-comparison";
    page: "/offers/compare";
  };
  "routes/salary-negotiation.tsx": {
    id: "routes/salary-negotiation";
    page: "/offers/negotiate";
  };
  "routes/equity-calculator.tsx": {
    id: "routes/equity-calculator";
    page: "/offers/equity";
  };
  "routes/benefits-analyzer.tsx": {
    id: "routes/benefits-analyzer";
    page: "/offers/benefits";
  };
  "routes/decision-framework.tsx": {
    id: "routes/decision-framework";
    page: "/offers/decide";
  };
  "routes/resignation-letter.tsx": {
    id: "routes/resignation-letter";
    page: "/offers/resign";
  };
  "routes/resumes.tsx": {
    id: "routes/resumes";
    page: "/resumes";
  };
  "routes/generate-resume.tsx": {
    id: "routes/generate-resume";
    page: "/resumes/new";
  };
  "routes/upload.tsx": {
    id: "routes/upload";
    page: "/resumes/upload";
  };
  "routes/batch-upload.tsx": {
    id: "routes/batch-upload";
    page: "/resumes/batch";
  };
  "routes/batch.tsx": {
    id: "routes/batch";
    page: "/resumes/batch/:id";
  };
  "routes/resumes.$id.tsx": {
    id: "routes/resumes.$id";
    page: "/resumes/:id";
  };
  "routes/resumes.$id.edit.tsx": {
    id: "routes/resumes.$id.edit";
    page: "/resumes/:id/edit";
  };
  "routes/cover-letter.tsx": {
    id: "routes/cover-letter";
    page: "/resumes/:id/cover-letter";
  };
  "routes/skill-gap.tsx": {
    id: "routes/skill-gap";
    page: "/resumes/:id/skill-gap";
  };
  "routes/interview-questions.tsx": {
    id: "routes/interview-questions";
    page: "/resumes/:id/interview-questions";
  };
  "routes/salary-estimate.tsx": {
    id: "routes/salary-estimate";
    page: "/resumes/:id/salary-estimate";
  };
  "routes/multi-jd.tsx": {
    id: "routes/multi-jd";
    page: "/resumes/:id/multi-jd";
  };
  "routes/templates.tsx": {
    id: "routes/templates";
    page: "/resumes/:id/templates";
  };
  "routes/resumes.$id.tailored.tsx": {
    id: "routes/resumes.$id.tailored";
    page: "/resumes/:id/tailored";
  };
  "routes/resume-versions.tsx": {
    id: "routes/resume-versions";
    page: "/resumes/:id/versions";
  };
  "routes/cover-letter-templates.tsx": {
    id: "routes/cover-letter-templates";
    page: "/cover-letter-templates";
  };
  "routes/linkedin-profile.tsx": {
    id: "routes/linkedin-profile";
    page: "/linkedin-profile";
  };
  "routes/portfolio.tsx": {
    id: "routes/portfolio";
    page: "/portfolio";
  };
  "routes/references.tsx": {
    id: "routes/references";
    page: "/references";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/wipe.tsx": {
    id: "routes/wipe";
    page: "/wipe";
  };
  "routes/onboarding-plan.tsx": {
    id: "routes/onboarding-plan";
    page: "/onboarding/plan";
  };
  "routes/onboarding-checklist.tsx": {
    id: "routes/onboarding-checklist";
    page: "/onboarding/checklist";
  };
  "routes/manager-alignment.tsx": {
    id: "routes/manager-alignment";
    page: "/onboarding/manager-alignment";
  };
  "routes/network-map.tsx": {
    id: "routes/network-map";
    page: "/onboarding/network-map";
  };
  "routes/skill-refresh.tsx": {
    id: "routes/skill-refresh";
    page: "/onboarding/skill-refresh";
  };
  "routes/first-90-days.tsx": {
    id: "routes/first-90-days";
    page: "/onboarding/first-90-days";
  };
  "routes/follow-up-emails.tsx": {
    id: "routes/follow-up-emails";
    page: "/follow-up-emails";
  };
};